get-glu/glu

glu.go
go.work.sum
pkg/controllers/controller.go

This updates the reconcile CLI to support reconciling across all controllers in the system with optional label selectors.
```
go run ./... reconcile FLAGS [pipeline] [controller]
FLAGS:
--all             (reconcile all controllers (ignores labels))
--label key=value (filter controllers by label key value pair)
```

feat: support reconciling multiple controllers with label predicate

---

internal/oci/oci.go

I was using the wrong parameter here in the lookup.

fix(oci): lookup cred using registry not repository

---

ui/package.json
ui/src/app/workflow.tsx

I kind of got nerd sniped by this. I wanted to learn more about react flow, so I could make some tweaks.
Then I read the spacing code and wondered about some of the choices.
Then I took a crack at making the spacing content aware (estimated based on content lengths).
Before:
After:

fix: calculate width and spacing based on relative estimated widths

---

cmd/experiment/experiment.go
config.go
glu.go
pipeline.go
pkg/cli/cli.go
pkg/core/core.go
pkg/phases/phases.go
pkg/triggers/schedule/schedule.go
server.go

I refactored some things. The only breaking change this time is that schedules are now just one implementation of the new `glu.Trigger` abstraction. This will be the entrypoint for other Trigger types in the future.
This depends on the UI promotion change (just where I started from).
AI Summary:
This pull request introduces several significant changes to the codebase, including the addition of new functionalities, refactoring of existing code, and improvements to the configuration and scheduling mechanisms. The most important changes are summarized below:
* Added a new `Config` utility in `config.go` to manage and cache configured sources, such as Git and OCI repositories, using glu's conventional configuration format. This includes methods for constructing and configuring instances of …

refactor: CLI package and triggers

---

.github/workflows/release.yml

Im going to just yolo try and get this to work without workflow run triggers.
Mostly because, I would have to write two workflows anyway, to handle passing in tags to the run.
Which ultimately means I dont test a main bit of what I want to be working.

feat: add gh workflow to publish ui tag on version tag

---

glu.go
server.go
ui/embed.go

Primarily, this change supports adding the UI via `glu.WithUI(ui.FS())` on a call to `glu.NewSystem(...)`.
I had to change the code slightly to attempt to pull the UI out of the embed dist folder and return the sub fs.
It panics if it cannot do this, which I think is fine and should only happen on the initialization of your system.

feat: expose UI embed as function

---

server.go
ui/src/components/node.tsx
ui/src/components/pipeline.tsx
ui/src/types/flow.ts
ui/src/types/pipeline.ts

This changes the way we get the digest for the UI to be through the resource interfaces `Digest()` method instead.
This puts the digest as a more consistent field on the response.
Doing so means that folks dont have to make a field that renders with the name `digest` in order to see this.

refactor: get digest through resource method

---

examples/fakedata/main.go
internal/oci/oci.go
pkg/core/core.go
pkg/phases/phases.go
pkg/src/git/source.go
pkg/src/oci/oci.go
server.go
ui/src/components/node.tsx
ui/src/components/pipeline.tsx
ui/src/types/flow.ts
ui/src/types/metadata.ts
ui/src/types/pipeline.ts

UI changes are temporary for now pending refactor to show a single pipeline at a time

feat: expose source metadata and add oci image url

---

config.go
docs/configuration.md
pkg/config/config_test.go
pkg/config/git.go

fix(config): add interval option for git configuration

---

examples/fakedata/main.go
ui/src/components/label.tsx
ui/src/components/node-panel.tsx
ui/src/components/node.tsx

Particularly useful in the walkthrough where I want to link to the staging and prod pages.

feat: make label values matching URLs clickable

---

ui/src/components/sidebar.tsx
ui/src/components/ui/sidebar.tsx

This pull request includes changes to the `ui/src/components/sidebar.tsx` and `ui/src/components/ui/sidebar.tsx` files to improve the functionality and styling of the sidebar component. 
The header uses p-4 and sidebar logo p-2, pt-4 is added to keep the same space in the top of the page.
Small logic is added to preselect current pipeline if the page is visited by direct link like `http://localhost/#/pipelines/checkout`

fix(ui): tweak sidebar logo and pipeline selector

---

pkg/core/core.go
pkg/triggers/schedule/schedule.go

Adding a core list predicate and matching schedule predicate for targeting a phase name `HasName`.
This is similar to `HasLabel` and returns all phases with the same name.
Useful if you consistently name phases the same across pipelines.

feat(triggers/schedule): add MatchName predicate

---

docs/_coverpage.md

chore: updates the docs coverpage to remove progressive delivery statement

---

pkg/builder/builder.go

This is important to avoid a footgun since the builder is stateful (stores previously observed errors to return on `Run()`).

fix(builder): override AddTrigger method expose through SystemBuilder

---

pkg/core/core.go
pkg/src/oci/oci.go
server.go
ui/src/components/node-panel.tsx
ui/src/components/node.tsx
ui/src/components/pipeline.tsx
ui/src/types/flow.ts
ui/src/types/pipeline.ts
ui/src/types/resource.ts

changes the structure a bit.
a phase now has:
1. metadata of its own (name, annotations, labels)
2. a source, which returns its own metadata
3. a resource, which is the state of the source in the phase, containing a digest, optional annotations, and info about if it is in sync of not with the source
4. depends_on, its parent phase
i also added a base resource in the OCI package which implements methods necessary for OCI resource to set its digest and annotations from the manifest
next we will add support for the common OCI annotations in the UI, like:
- `org.opencontainers.image.url`
- `org.opencontainers.image.source`
- `org.opencontainers.image.revision`

feat: support resource annotations

---

pkg/credentials/credentials.go

I'm not 💯 certain GitHub App authentication works at all with packages after reading this Discussion:
https://github.com/orgs/community/discussions/24636
But, I thought I would take a stab at it, the way I have effectively done GH app for git pulls is similar to this approach.
I am using the gh installation package transport as my token cache and fetcher.
Then I am setting it as basic auth creds on the OCI pull.
GH expects this for git pull, I can't say if it will work for packages in a similar way.
Going to get this in and give it a try though.

feat(credentials): attempt to support GH app for OCI/packages

---

pkg/src/oci/oci.go

This is a slight refactor make the interfaces a little friendlier.
It attempts a best effort to use the most typed path to getting all necessary information.
I added the ability optionally define both:
```go
ReadFromOCIManifest(v1.Descriptor, v1.Manifest) error
ReadFromOCIIndex(v1.Descriptor, v1.Index) error
```
Now on `View` we switch on the media type of the descriptor and an unexected typed (index or manifest) we attempt to use the relevant `ReadFromOCIManifest` or `ReadFromOCIIndex`.
The BaseResource implements both and so should work for either case depending on what it resolves to.
This removes the need to pass the more opaque reader into `ReadFromOCIDescriptor`.
If it doesn't recognise the type it just attempts the `content.ReadAll` approach automatically into the descriptor (to …

refactor(src/oci): add support for read from index and manifest

---

pkg/cli/cli.go
pkg/core/core.go
pkg/phases/phases.go
pkg/scm/github/github.go
pkg/src/git/source.go
pkg/triggers/schedule/schedule.go
server.go
ui/src/components/node.tsx
ui/src/services/api.ts
ui/src/types/metadata.ts
ui/src/types/pipeline.ts

There are a few extra cleanup details I slipped into this PR.
However, the main aim is to feed forward details from the source update to the UI through a new result type returned on propose.

feat: add pull request URL to success toast on propose

---

glu.go

Fixes:
```
time=2024-12-02T12:44:33.695-05:00 level=ERROR msg="error running mock server" error="creating metrics resource: error detecting resource: conflicting Schema URL: https://opentelemetry.io/schemas/1.17.0 and https://opentelemetry.io/schemas/1.26.0"
```

fix: metrics import issue

---

examples/fakedata/main.go
examples/oci-and-git/experiment.go
ui/src/components/button-edge.tsx
ui/src/components/node-panel.tsx
ui/src/components/pipeline.tsx
ui/src/types/flow.ts

- fixes node-panel errors
- removes 'depends on' from node panel as it would now require passing in the edges too, can do this if we think its useful to put back though
- adds a bit of space between the edge and the promote icon as it looked weird in light mode when they overlapped

chore: fix ui

---

docs/concepts.md
docs/guides/gitops-implementation.md
examples/fakedata/main.go
examples/oci-and-git/experiment.go
glu.go
pkg/pipelines/pipelines.go

Quick change to adjust how context and config gets threaded onto the pipelines builder.
Now it just passes the whole system to the builder.
This simplfies some things when using the builder.

refactor: pass entire system to pipelines.NewBuilder

---

pkg/core/pipeline.go
pkg/core/typed/typed.go
pkg/edges/edges.go
pkg/phases/git/source.go
pkg/phases/oci/oci.go
pkg/pipelines/pipelines.go
pkg/reflog/log.go
pkg/triggers/schedule/schedule.go
server.go

Supports #97
This adds the APIs and server-side functionality for rolling a phase back to a previously known version in time.
The changes introduces the new interface:
```go
type RollbackPhase interface {
Phase
Rollback(context.Context, uuid.UUID) error
}
```
This is an interface upgrade target which the server attempts when you try to do:
```
POST /api/v1/pipelines/{pipeline}/phases/{phase}/rollback/{version}
```
Which is the new endpoint used to rollback to a known version.
The version should first be obtained through the history endpoint.
The operation will fail if the version is no longer in history.
I am still validating it works as expected, but this is the initial implementation.
I will update this description when I have validated it.

feat(phases/git): implement rollback on the server side

---

ui/src/app/layout.tsx
ui/src/app/pipeline.tsx
ui/src/components/header.tsx
ui/src/components/sidebar.tsx
ui/src/store/index.ts
ui/src/store/pipelinesSlice.ts

adds back the `selectedPipeline` and moves the header back to the main layout. it looked weird without it.
This now works without the re-rendering

fix: header in ui

---

go.work.sum
internal/git/repository.go
pkg/phases/git/source.go
ui/src/components/label.tsx
ui/src/components/phase-history.tsx
ui/src/components/phase-state-details.tsx
ui/src/types/metadata.ts

Fixes: #111 
its very hacky for now as it only supports links that start with `github.com`, but we can clean up the logic/abstract it in the future to support other SCMs

feat: add link to github commit in history

---

glu.go
pkg/phases/git/git.go
pkg/triggers/schedule/schedule.go
pkg/triggers/triggers.go

I borked this in the refactor leading to promotions only happening once on startup.
This removes the returns from the schedule and lets it continue under all circumstrances apart from context cancellation.

fix(triggers): continue on skipped and error conditions in schedule

---

internal/git/repository.go
pkg/phases/git/git.go
pkg/phases/logger/logger.go
pkg/scm/github/github.go

This change does a number of things for the PR / proposal lifecycle:
1. It caches previously fetched / created proposals on the Phase itself.
This avoids us doing more costly paginated walks to locate previously created open PRs associated with the phase on each attempt to promote.
2. It adjust the flow to close existing PRs
When a new version is observed and an existing PR is open, then the update code will close the existing PR first, then push to the new branch and open a new PR. It adds a comment to the old PR linking to the new one for clarity.
Here is what the robots say:
This pull request includes significant changes to the `internal/git/repository.go` and `pkg/phases/git/git.go` files, focusing on refactoring and enhancing the branch and proposal handling mechanisms. The changes …

refactor(phase/git): rework proposal process

---

.gitignore
collector.yaml
internal/config/config_test.go
otel/receiver/k8sreceiver/factory.go
otel/receiver/k8sreceiver/oci.go
otel/receiver/k8sreceiver/receiver.go

support pulling using plain HTTP from oci repos

chore: support pulling with plain http in k8s receiver
